# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20171012_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='routeCode',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='routes',
            name='routeName',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stopCode',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stopName',
            field=models.TextField(max_length=255),
        ),
    ]
